root: ./

redirects:
  getting-started/faq-1/requirements-and-troubleshooting: getting-started/faq-1/teams-and-billing.md
  getting-started/faq-1/editor-and-runtimes: https://rive.app/community/doc/introduction/docvphVOrBbl