root: ./

redirects:
  getting-started/faq-1: https://rive.app/community/forums/faq/fsKixNVwMqiY
  getting-started:
    faq-1: https://rive.app/community/forums/faq/fsKixNVwMqiY
  getting-started/faq-1/editor-and-runtimes: https://rive.app/community/forums/faq/fsKixNVwMqiY
